In [1]:
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import statsmodels.api as sm
import itertools
import scipy as sp

In [8]:
#load the data and check it out

data = pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv', header = 1)
data

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
242,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
243,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
244,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
245,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [ ]:
# Cleaning data

In [9]:
# Normalize Data

data_norm = (data - data.mean())/data.std()
data_norm

TypeError: can only concatenate str (not "int") to str

In [ ]:
 # MLR 
    
    
    
varx = "x"
vary =  "y"


X = np.array(data[varx]).reshape(-1, 1)  

# X = data[["x", "x2", "x3"]]   # Alternative

y = data[vary]


# # If I include the whole data set as X, should I drop Y or all the other xs? 


lm_MLR = linear_model.LinearRegression()
model = lm_MLR.fit(X,y)
ypred_MLR = lm_MLR.predict(X) #y predicted by MLR
intercept_MLR = lm_MLR.intercept_ #intercept predicted by MLR
coef_MLR = lm_MLR.coef_ #regression coefficients in MLR model
R2_MLR = lm_MLR.score(X,y) #R-squared value from MLR model
corr_coef = np.corrcoef(ypred_MLR,y) # Pearson correlation between modeled and target y
print('correlation = ' + str(corr_coef[0, 1]))

fig, ax = plt.subplots(1,3, figsize=(20,4))


ax[0].scatter(data[varx],y)
ax[0].plot(data[varx],ypred_MLR, ls = "solid", c ="r")
ax[0].set_title(f"{varx} vs {vary}, R^2 = {round(R2_MLR,3)}")
ax[0].set_xlabel(varx)   
ax[0].set_ylabel(vary)